### PR TITLE
Test

### PR DESCRIPTION
**Pull request by hrishikesh34**
The NHL preprocessing file seperated in 3. One for each dataset.

### CODE REVIEW

**Comment by maxkitman** [comment]
@hrishikesh34 - if the 3 new files include all the data you wanted to push initially in the `NHL_preprocessing` file, delete that file and commit this change so it is not part of the code to review and push anymore.

**Comment by hrishikesh34** [comment]
@maxkitman I have removed the file. Is it okay now?

**Review by maxkitman — APPROVED** [review]
Looks good. Few things : 
- I actually found a way to read the bigger file that was 2k rows so it won't be an issue in the future. This was due to the code including notebook cell information. Jupyter Notebooks are not great to push on GH. We're not going to change that now but it might be better to use a code editor like VS Code. With this, you could push certain lines and not a full file each time, it's very handy.
- Another PR name would be better than test in the future
- The ideal flow for PR review is to create an issue (in GH next to pull request) and link that issue to a PR. Each PR solves an issue and then close it. For instance, if you plan on pushing code to scrape data, you can create a GH issue called "NHL Schedule - Scrape data" and then link that issue in the PR. If you write "closes <<copy_issue_url>>" in the PR, it will automatically close the issue when the PR is merged

**Comment by maxkitman** [comment]
Hey @hrishikesh34, do you want to merge that pull request so you don't push unintentionally code to this? Except if you wanna change anything to it before

**Comment by hrishikesh34** [comment]
Apologies. Merged the pull request now.

**Pull request merged**
